### ISSUE TITLE
Return value of "com.meteordevelopments.duels.DuelsPlugin.getUpdateManager()" is null

### ISSUE THREAD

**Issue by smscentras** [dumbo-the-developer/Duels#42]
### Server version

Purpur 1.21.1

### Duels version

1.3

### Plugin list

Problem not in other plugins

### Describe the bug

[09:40:07] [Server thread/WARN]: [Duels] Task #307 for Duels v1.3 generated an exception
java.lang.NullPointerException: Cannot invoke "com.meteordevelopments.duels.util.UpdateManager.updateIsAvailable()" because the return value of "com.meteordevelopments.duels.DuelsPlugin.getUpdateManager()" is null
    at Duels-Optimised-1.3.jar/com.meteordevelopments.duels.data.UserManagerImpl.lambda$on$7(UserManagerImpl.java:282) ~[Duels-Optimised-1.3.jar:?]
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1761) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
    at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Expected behavior

Error when start server

### Steps to reproduce

You need latest plugin version and start server.

### Checklist

- [X] I am running latest version of the plugin
- [X] #43
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
So you ticked all the boxes without reading and this issue not not happening with me
