### ISSUE TITLE
Error On PvP With Use Own Inventory

### ISSUE THREAD

**Issue by ColdSight** [dumbo-the-developer/Duels#45]
### Server version

Paper (Pufferfish) 1.21.1

### Duels version

1.3

### Plugin list

N/A

### Describe the bug

Every player hit (when bringing in own inventory) an error gets sent to console.

### Expected behavior

No errors in console.

### Steps to reproduce

- Send a duel with use own inventory enabled
- In duel, hit the opposing player
- Error spams in console on every hit

### Additional info

[18:40:41 ERROR]: Could not pass event EntityDamageByEntityEvent to Duels v1.3
java.lang.NullPointerException: Cannot invoke "com.meteordevelopments.duels.kit.KitImpl.getCharacteristics()" because the return value of "com.meteordevelopments.duels.arena.MatchImpl.getKit()" is null
        at Duels-Optimised-1.3.jar/com.meteordevelopments.duels.listeners.DamageListener.onDamage(DamageListener.java:49) ~[Duels-Optimised-1.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1328.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-18-63ce67d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2353) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1500) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1344) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2420) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2880) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2791) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-18-63ce67d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by smscentras** [comment]
I confirm, same problem.
Purpur 1.21.1
Duels 1.4

**Comment by dumbo-the-developer** [comment]
fixed in latest commit. ill update plugin soon
