### ISSUE TITLE
Unhandled exception executing command '1v1' in plugin Duels v1.6

### ISSUE THREAD

**Issue by smscentras** [dumbo-the-developer/Duels#50]
### Server version

Purpur 1.21.1

### Duels version

1.6

### Plugin list

Not there is problem

### Describe the bug

Can't play game, error.

### Expected behavior

[08:49:01] [Server thread/ERROR]: Command exception: /1v1 NickName
org.bukkit.command.CommandException: Unhandled exception executing command '1v1' in plugin Duels v1.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2311-0fa9a50]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "com.meteordevelopments.duels.config.Lang.getMessage(String)" is null
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.gui.settings.buttons.OwnInventoryButton.<init>(OwnInventoryButton.java:14) ~[Duels-Optimised-1.6.jar:?]
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.gui.settings.SettingsGui.<init>(SettingsGui.java:40) ~[Duels-Optimised-1.6.jar:?]
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.setting.Settings.<init>(Settings.java:41) ~[Duels-Optimised-1.6.jar:?]
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.setting.SettingsManager.lambda$getSafely$0(SettingsManager.java:36) ~[Duels-Optimised-1.6.jar:?]
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.setting.SettingsManager.getSafely(SettingsManager.java:36) ~[Duels-Optimised-1.6.jar:?]
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.command.commands.duel.DuelCommand.executeFirst(DuelCommand.java:148) ~[Duels-Optimised-1.6.jar:?]
	at Duels-Optimised-1.6.jar/com.meteordevelopments.duels.util.command.AbstractCommand.lambda$register$0(AbstractCommand.java:113) ~[Duels-Optimised-1.6.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 27 more

### Steps to reproduce

/1v1 Nickname

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by smscentras** [comment]
With version 1.5 all ok

**Comment by dumbo-the-developer** [comment]
Update your lang config with latest config
