### ISSUE TITLE
[!] Version 1.9 allways show bug after battle ends

### ISSUE THREAD

**Issue by smscentras** [dumbo-the-developer/Duels#55]
### Server version

Purpur 1.21.1

### Duels version

1.9

### Plugin list

noone

### Describe the bug

Found in LOG, when duel started.

### Expected behavior

````
[14:52:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[14:52:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.compat.Skulls.setProfile(Skulls.java:71)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.lambda$setOwner$2(Button.java:55)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.editMeta(Button.java:37)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.setOwner(Button.java:55)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.gui.inventory.buttons.HeadButton.<init>(HeadButton.java:17)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.gui.inventory.InventoryGui.<init>(InventoryGui.java:19)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.inventories.InventoryManager.create(InventoryManager.java:61)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.duel.DuelManager$DuelListener.on(DuelManager.java:541)
[14:52:29] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[14:52:29] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:52:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:52:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:52:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[14:52:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[14:52:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1039)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1057)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1651)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.world.entity.player.Player.hurt(Player.java:1041)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.world.entity.player.Player.attack(Player.java:1383)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2544)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onAttack(ServerGamePacketListenerImpl.java:2961)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2870)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[14:52:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[14:52:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[14:52:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.compat.Skulls.setProfile(Skulls.java:71)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.lambda$setOwner$2(Button.java:55)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.editMeta(Button.java:37)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.setOwner(Button.java:55)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.gui.inventory.buttons.HeadButton.<init>(HeadButton.java:17)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.gui.inventory.InventoryGui.<init>(InventoryGui.java:19)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.inventories.InventoryManager.create(InventoryManager.java:61)
[14:52:29] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.duel.DuelManager$DuelListener.lambda$on$6(DuelManager.java:561)
[14:52:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[14:52:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1761)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333)
[14:52:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[14:52:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
````

### Steps to reproduce

Found in LOG.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by smscentras** [comment]
Everytime when players END battle - this error occour!

**Comment by dumbo-the-developer** [comment]
Fixed
