### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by VitzS7ven** [dumbo-the-developer/Duels#58]
### Server version

1.21.1 Paper/Bukkit

### Duels version

1.9

### Plugin list

[00:57:49 INFO]: Server Plugins (85):
[00:57:49 INFO]: Paper Plugins:
[00:57:49 INFO]:  - EconomyShopGUI-Premium, RoseStacker
[00:57:49 INFO]: Bukkit Plugins:
[00:57:49 INFO]:  - Admin-GUI, AdvancedChests, ajLeaderboards, *AntiLoggedInFromAnotherLocation, AuraSkills, AutoMessage, AutoPickup, BetterCommandSpy, BetterRTP, BloodMoon
[00:57:49 INFO]:  ChatColor2, ChestSort, Chunky, CleanroomGenerator, ClearLag, CoreProtect, CratesPlus, DecentHolograms, DiscordSRV, Duels
[00:57:49 INFO]:  Elevator, Essentials, EssentialsChat, EssentialsWarpGUI, floodgate, Geyser-Spigot, GHomeGuiForEssentialsX, GravesX, GriefPrevention, GSit
[00:57:49 INFO]:  HeadDrop, HealthBar, Hurricane, *Invsee_v1.0.3, ItemsAdder, LagAssist, LeafDiscord, LeafMedals, LeafMito, LeafPlugins
[00:57:49 INFO]:  LeafPunish, LeafStatsView, LeafTags, *LightN, LoneLibs, LuckPerms, Multiverse-Core, MyCommand, nChat, nLogin
[00:57:49 INFO]:  Orebfuscator, packetevents, PlaceholderAPI, PlayerAuctions, PlayerKits2, PlayerReport, ProtocolLib, PvPManager, RealScoreboard, ServersNPC
[00:57:49 INFO]:  SimpleClans, *SimpleSit, SkinsRestorer, StackMob, SuperVanish, TAB, TradeSystem, *Trash, TreeFeller, UltimateAutoRestart
[00:57:49 INFO]:  UltraCosmetics, UniversalProtocol, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, ViewDistanceTweaks, voicechat, Vulcan
[00:57:49 INFO]:  WorldEdit, WorldGuard, XCatch

### Describe the bug

[00:53:25 INFO]: [DuelsOptimised] Registering commands...
[00:53:25 INFO]: [DuelsOptimised] Successfully registered commands [0ms]
[00:53:25 INFO]: [DuelsOptimised] Loaded 6 kit(s).
[00:53:25 INFO]: [DuelsOptimised] Loaded 0 arena(s).
[00:53:25 INFO]: [DuelsOptimised] Loaded 0 queue(s).
[00:53:25 INFO]: [DuelsOptimised] Loaded 0 queue sign(s).
[00:53:25 INFO]: [Duels] ExtensionManager: Could not load extension Placeholders-1.0.4.jar: This extension requires Duels v3.5.1 or higher!
[00:53:25 INFO]: [Duels] ExtensionManager: Could not enable extension Certificates-1.0.2.jar!
[00:53:25 WARN]: java.lang.NoClassDefFoundError: me/realized/duels/api/extension/DuelsExtension
[00:53:25 WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[00:53:25 WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
[00:53:25 WARN]:        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[00:53:25 WARN]:        at io.papermc.reflectionrewriter.runtime.DefineClassReflectionProxyImpl.defineClass(DefineClassReflectionProxyImpl.java:109)
[00:53:25 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflection.defineClass(PaperReflection.java:189)
[00:53:25 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.defineClass(Unknown Source)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.extension.ExtensionClassLoader.findClass(ExtensionClassLoader.java:83)
[00:53:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[00:53:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[00:53:25 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[00:53:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[00:53:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.extension.ExtensionClassLoader.<init>(ExtensionClassLoader.java:36)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.extension.ExtensionManager.handleLoad(ExtensionManager.java:70)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.DuelsPlugin.load(DuelsPlugin.java:230)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.DuelsPlugin.reload(DuelsPlugin.java:329)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.command.commands.duels.subcommands.ReloadCommand.execute(ReloadCommand.java:42)
[00:53:25 WARN]:        at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.command.AbstractCommand.lambda$register$0(AbstractCommand.java:140)
[00:53:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:53:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
[00:53:25 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001)
[00:53:25 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:986)
[00:53:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526)
[00:53:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[00:53:25 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596)
[00:53:25 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302)
[00:53:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[00:53:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[00:53:25 INFO]: [Duels] ExtensionManager: Could not load extension Leaderboards-1.1.2.jar: This extension requires Duels v3.3.0 or higher!
[00:53:25 INFO]: [Duels v1.9] Reload complete.
[00:53:25 INFO]: [DuelsOptimised] Registering listeners...
[00:53:25 INFO]: [DuelsOptimised] Successfully registered listeners [0ms]

### Expected behavior

it was supposed to work

### Steps to reproduce

step 1: download extensions and put them in extensions folder
step 2: do /duels reload

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
Old extensions are not supported

**Comment by VitzS7ven** [comment]
how dowload the new?
