### ISSUE TITLE
net.minecraft.world.item.component.ResolvableProfile

### ISSUE THREAD

**Issue by bobhenl** [dumbo-the-developer/Duels#71]
### Server version

Purpur 1.21.1

### Duels version

1.9

### Plugin list

[20:28:21 INFO]: Paper Plugins: (1):
[20:28:21 INFO]:  - EconomyShopGUI-Premium
[20:28:21 INFO]: Bukkit Plugins: (145):
[20:28:21 INFO]:  - AdvancedEnderchest, AdvancedReplay, AFKRewardsAuth, ajLeaderboards, ajParkour, AmazingTitles, AngleGuard, AntiAura-ESP, AntiCheatReplay, AsteroidLibs
[20:28:21 INFO]:  AutoSmelt, BattlePass, BestTools, BetterRTP, BlockRegen, Boatglitchprevent, BottledExp, CenterStick, ChatControlRed, ChatEmojis
[20:28:21 INFO]:  ChestPreview, ChestSort, ChristmasPlus, Chunky, Citizens, CMI, CMILib, CommandAPI, CommandBridge, ConsoleSpamFix
[20:28:21 INFO]:  CoreProtect, CrazyEnvoys, CrazyVouchers, CustomPlaceholders, DecentHolograms, DeluxeCoinflip, DeluxeCombat, DeluxeMenus, DisableSignEdit, DiscordChangelog
[20:28:21 INFO]:  DiscordSRV, DragonSlayer, DragonTimer, Drop2InventoryPlus, Duels, dynmap, EmailerContinued, EntitySize, EternalTags, ExtraContexts
[20:28:21 INFO]:  Factions, FancyPhysics, FastAsyncWorldEdit, FasterCrystals, FileCleaner, floodgate, ForcePack, GeoTebexCoupons, GSit, HeadDatabase
[20:28:21 INFO]:  HoloMobHealth, HubPvP, IllegalStack, ImageFireworksPro, ImageFrame, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, InvUnload
[20:28:21 INFO]:  ItemPrices, ItemsAdder, JumpPads, LagAssist, Lib1711, LibsDisguises, LifeStealZ, LiteBans, LoneLibs, LuckPerms
[20:28:21 INFO]:  MobFarmManager, MoneyFromMobs, MoneyPouchDeluxe, Multiverse-Core, NameMC, NBTAPI, NetworkInterceptor, nightcore, *NightVision, packetevents
[20:28:21 INFO]:  PhysicsToGo, Pl-Hide-Pro, PlaceholderAPI, Plan, PlayerPoints, PlugManX, Polymart, ProtocolLib, pvpstats, RandomEvents
[20:28:21 INFO]:  RawMsg, Referral, RegionPlaceholder, SecureBeds, SecureStorage, SelectionVisualizer, ServerTutorialPlus, SkinsRestorer, SmoothSleep, Snowballs
[20:28:21 INFO]:  SpawnerMeta, SpecializedCrates, StoreStats, StreamingDrops, StreamSpectate, SurveyPlus, TAB, Tebex, TheCore, Themis
[20:28:21 INFO]:  TheRewards, ThrowableSpawnEggs, ToastedAFK, TradeMe, TrailGUI, TryMe, UIFramework, UltimateContent, UltraCosmetics, Vault
[20:28:21 INFO]:  Vegas, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, ViaVersionStatus, VillagerMarket, VoidTeleportPlus, Voting, VotingPlugin
[20:28:21 INFO]:  Vulcan, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3, zMenu

### Describe the bug

Hello, I'm getting this bug
```yml
[18:50:22] [Server thread/INFO]: ☠ N1gh1m4res ❤10 was killed by [Intentional Game Design]
[18:50:22] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[18:50:22] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[18:50:22] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[18:50:22] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[18:50:22] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.compat.Skulls.setProfile(Skulls.java:71)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.lambda$setOwner$2(Button.java:55)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.editMeta(Button.java:37)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.util.gui.Button.setOwner(Button.java:55)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.gui.inventory.buttons.HeadButton.<init>(HeadButton.java:17)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.gui.inventory.InventoryGui.<init>(InventoryGui.java:19)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.inventories.InventoryManager.create(InventoryManager.java:61)
[18:50:22] [Server thread/WARN]: 	at Duels-Optimised-1.9.jar//com.meteordevelopments.duels.duel.DuelManager$DuelListener.on(DuelManager.java:541)
[18:50:22] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44)
[18:50:22] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:50:22] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:50:22] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:50:22] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[18:50:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[18:50:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1039)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1057)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1651)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.entity.player.Player.hurt(Player.java:1041)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.Explosion.explode(Explosion.java:594)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1573)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1861)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1528)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1519)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.block.RespawnAnchorBlock.explode(RespawnAnchorBlock.java:153)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.block.RespawnAnchorBlock.useWithoutItem(RespawnAnchorBlock.java:83)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.useWithoutItem(BlockBehaviour.java:1247)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:591)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2020)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1673)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342)
[18:50:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[18:50:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Expected behavior

No error

### Steps to reproduce

Not sure, let me know if needed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
Fixed
