### ISSUE TITLE
Spam console

### ISSUE THREAD

**Issue by bobhenl** [dumbo-the-developer/Duels#72]
### Server version

Purpur 1.21.1

### Duels version

2.0

### Plugin list

16:18:32 INFO]: Bukkit Plugins: (149):
[16:18:32 INFO]:  - AdvancedEnderchest, AdvancedReplay, AFKRewardsAuth, ajLeaderboards, ajParkour, AmazingTitles, AngleGuard, AntiAura-ESP, AntiCheatReplay, AsteroidLibs
[16:18:32 INFO]:  AutoSmelt, BattlePass, BestTools, BetterRTP, BlockRegen, Boatglitchprevent, BottledExp, CenterStick, ChatControlRed, ChatEmojis
[16:18:32 INFO]:  ChestPreview, ChestSort, ChristmasPlus, Chunky, Citizens, CMI, CMILib, CommandAPI, CommandBridge, ConsoleSpamFix
[16:18:32 INFO]:  CoreProtect, CrazyEnvoys, CrazyVouchers, CustomPlaceholders, DecentHolograms, DeluxeCoinflip, DeluxeCombat, DeluxeMenus, DisableSignEdit, DiscordChangelog
[16:18:32 INFO]:  DiscordSRV, DragonSlayer, DragonTimer, Drop2InventoryPlus, Duels, Duels, dynmap, EmailerContinued, EntitySize, EternalTags
[16:18:32 INFO]:  ExtraContexts, Factions, FancyPhysics, FastAsyncWorldEdit, FasterCrystals, FileCleaner, floodgate, ForcePack, GadgetsMenu, GeoTebexCoupons
[16:18:32 INFO]:  GrapplingHook, GSit, *Hazard_AntiSuffocate, HeadDatabase, HoloMobHealth, HubPvP, IllegalStack, ImageFireworksPro, ImageFrame, InteractionVisualizer
[16:18:32 INFO]:  InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, InvUnload, ItemPrices, ItemsAdder, JumpPads, LagAssist, Lib1711, LibsDisguises
[16:18:32 INFO]:  LifeStealZ, LiteBans, LoneLibs, LuckPerms, MobFarmManager, MoneyFromMobs, MoneyPouchDeluxe, Multiverse-Core, NameMC, NBTAPI
[16:18:32 INFO]:  NetworkInterceptor, nightcore, *NightVision, packetevents, PhysicsToGo, Pl-Hide-Pro, PlaceholderAPI, Plan, PlayerPoints, PlugManX
[16:18:32 INFO]:  Polymart, ProtocolLib, pvpstats, RandomEvents, RawMsg, Referral, RegionPlaceholder, SecureBeds, SecureStorage, SelectionVisualizer
[16:18:32 INFO]:  ServerTutorialPlus, SkinsRestorer, SmoothSleep, Snowballs, SpawnerMeta, SpecializedCrates, StoreStats, StreamingDrops, StreamSpectate, SurveyPlus
[16:18:32 INFO]:  TAB, Tebex, TheCore, Themis, TheRewards, ThrowableSpawnEggs, ToastedAFK, TradeMe, TrailGUI, TryMe
[16:18:32 INFO]:  UIFramework, UltimateContent, UltraCosmetics, Vault, Vegas, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, ViaVersionStatus
[16:18:32 INFO]:  VillagerMarket, VoidTeleportPlus, Voting, VotingPlugin, Vulcan, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3, zMenu

### Describe the bug

Hello, after every Duel there's big spam so I downgraded to the previous version.
```yml
[16:18:59 WARN]: [Duels] Plugin Duels v2.0 generated an exception while executing task 47827835
java.lang.IllegalStateException: Not scheduled yet
        at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:156) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:150) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:30) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Duels-Optimised-2.0-1734103709754.jar/com.meteordevelopments.duels.countdown.DuelCountdown.run(DuelCountdown.java:89) ~[Duels-Optimised-2.0-1734103709754.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Expected behavior

No spam.

### Steps to reproduce

Just go to Duel & end, and then you'll see spam

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
Fixed
