### ISSUE TITLE
provided key 'DUEL.on-death.with-killer' has no assigned value

### ISSUE THREAD

**Issue by smscentras** [dumbo-the-developer/Duels#73]
### Server version

Purpur 1.21.1

### Duels version

2.1

### Plugin list

...

### Describe the bug

```
[09:01:46] [Server thread/INFO]: [Duels] Lang: Failed to load message: provided key 'DUEL.on-death.with-killer' has no assigned value
[09:01:46] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Duels v2.1
java.lang.IllegalArgumentException: message cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:387) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:382) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.entity.CraftPlayer.sendMessage(CraftPlayer.java:399) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at Duels-Optimised-2.1.jar/com.meteordevelopments.duels.arena.ArenaImpl.lambda$broadcast$2(ArenaImpl.java:274) ~[Duels-Optimised-2.1.jar:?]
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1016) ~[?:?]
	at Duels-Optimised-2.1.jar/com.meteordevelopments.duels.arena.ArenaImpl.broadcast(ArenaImpl.java:274) ~[Duels-Optimised-2.1.jar:?]
	at Duels-Optimised-2.1.jar/com.meteordevelopments.duels.duel.DuelManager$DuelListener.on(DuelManager.java:420) ~[Duels-Optimised-2.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1039) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1057) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1651) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1041) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1383) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2544) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onAttack(ServerGamePacketListenerImpl.java:2961) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2870) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Expected behavior

Where i can find DUEL.on-death.with-killer?

### Steps to reproduce

After every battle end.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by youge-grass** [comment]
same

**Comment by Rzaba222** [comment]
same, plugin doesn't work at all randomly after a server restart, match doesn't start and players can't leave the arena, they lose their items too

**Comment by smscentras** [comment]
> same, plugin doesn't work at all randomly after a server restart, match doesn't start and players can't leave the arena, they lose their items too

yes, sometimes last player which leave arena - loosing all items.

**Comment by smscentras** [comment]
There is new lines in language file:
  "on-death:"
  "on-end:"
But plugin did not update old file and we have errors.
**and what's most interesting, the programmer didn't tell anyone about it**
